/**
 * api-gateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ApiError } from '../common/apiError';


export interface BaseResponse<T> {
    status: string;
    code: number;
    message?: string;
    result?: T;
    error?: ApiError;
    success?: boolean;
}
